[package]
name = "enforce-draft-pr"
version.workspace = true
edition = "2024"

[[bin]]
name = "enforce-draft-pr"
path = "src/main.rs"

[dependencies]
hook-common.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
anyhow.workspace = true
