[package]
name = "auto-create-pr"
version.workspace = true
edition = "2024"

[[bin]]
name = "auto-create-pr"
path = "src/main.rs"

[dependencies]
hook-common.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
