[package]
name = "ensure-noreply-email"
version.workspace = true
edition = "2024"

[[bin]]
name = "ensure-noreply-email"
path = "src/main.rs"

[dependencies]
hook-common.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
